# Generated by Django 3.0.6 on 2021-01-17 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='Title')),
                ('title_uk', models.CharField(db_index=True, max_length=255, null=True, verbose_name='Title')),
                ('title_ru', models.CharField(db_index=True, max_length=255, null=True, verbose_name='Title')),
                ('address', models.CharField(db_index=True, max_length=255, verbose_name='Address')),
                ('address_uk', models.CharField(db_index=True, max_length=255, null=True, verbose_name='Address')),
                ('address_ru', models.CharField(db_index=True, max_length=255, null=True, verbose_name='Address')),
            ],
            options={
                'verbose_name': 'Warehouse',
                'verbose_name_plural': 'Warehouses',
            },
        ),
    ]
