# Generated by Django 3.0.6 on 2021-01-17 14:23

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(blank=True, max_length=20, verbose_name="Контактне ім'я")),
                ('email', models.CharField(blank=True, max_length=50)),
                ('subject', models.CharField(blank=True, max_length=50, verbose_name='Тема повідомлення')),
                ('comment', models.TextField(blank=True, max_length=255, verbose_name='Текст повідомлення')),
                ('status', models.CharField(choices=[('New', 'New'), ('Read', 'Read'), ('Closed', 'Closed')], default='New', max_length=10, verbose_name='Статус')),
                ('note', models.CharField(blank=True, max_length=100, verbose_name='Примітка')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Повідомлення',
                'verbose_name_plural': 'Повідомлення',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Мова')),
                ('code', models.CharField(max_length=5, verbose_name='Код')),
                ('status', models.BooleanField(verbose_name='Статус')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Мова',
                'verbose_name_plural': 'Мова',
            },
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Назва')),
                ('keywords', models.CharField(max_length=255, verbose_name='Ключові слова')),
                ('description', models.CharField(max_length=255, verbose_name='Опис')),
                ('company', models.CharField(max_length=50, verbose_name='Компанія')),
                ('address', models.CharField(blank=True, max_length=100, verbose_name='Адреса')),
                ('phone', models.CharField(blank=True, max_length=15, verbose_name='Телефон')),
                ('fax', models.CharField(blank=True, max_length=15, verbose_name='Факс')),
                ('email', models.CharField(blank=True, max_length=50)),
                ('smtpserver', models.CharField(blank=True, max_length=50)),
                ('smtpemail', models.CharField(blank=True, max_length=50)),
                ('smtppassword', models.CharField(blank=True, max_length=10)),
                ('smtpport', models.CharField(blank=True, max_length=5)),
                ('icon', models.ImageField(blank=True, upload_to='images/', verbose_name='Іконка')),
                ('facebook', models.CharField(blank=True, max_length=50)),
                ('instagram', models.CharField(blank=True, max_length=50)),
                ('twitter', models.CharField(blank=True, max_length=50)),
                ('youtube', models.CharField(blank=True, max_length=50)),
                ('aboutus', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Про компанію')),
                ('shipmentpayment', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Доставка та Оплата')),
                ('warranty', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Гарантія')),
                ('purchasereturn', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Повернення товару')),
                ('status', models.CharField(choices=[('True', 'True'), ('False', 'False')], max_length=10, verbose_name='Статус')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Налаштування: українська мова',
                'verbose_name_plural': 'Налаштування: українська мова',
            },
        ),
        migrations.CreateModel(
            name='SettingLang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(choices=[('uk', 'Українська'), ('ru', 'Русский')], max_length=6, verbose_name='Мова')),
                ('title', models.CharField(max_length=150, verbose_name='Назва')),
                ('keywords', models.CharField(max_length=255, verbose_name='Ключові слова')),
                ('description', models.CharField(max_length=255, verbose_name='Опис')),
                ('aboutus', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Про компанію')),
                ('shipmentpayment', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Доставка та Оплата')),
                ('warranty', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Гарантія')),
                ('purchasereturn', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Повернення товару')),
                ('setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Setting', verbose_name='Налаштування')),
            ],
            options={
                'verbose_name': 'Налаштування: російська мова',
                'verbose_name_plural': 'Налаштування: російська мова',
            },
        ),
    ]
